modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://github.com/EnvyWare/ReforgedBingo/issues"

[[mods]]
modId="reforgedbingo"
version="2.9.1"
displayName="Reforged Bingo Forge"
displayURL="https://github.com/EnvyWare"
credits="https://github.com/EnvyWare"
authors="https://github.com/EnvyWare"
description='''
Adds Bingo
'''

[[dependencies.reforgedbingo]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.reforgedbingo]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"